services:
  redis:
    image: redis:7-alpine
    restart: always
    # REMOVED public port exposure - Redis only accessible via internal Docker network
    volumes:
      - redis-data:/data
    command: >
      sh -c "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD --maxmemory 512mb --maxmemory-policy noeviction"
    healthcheck:
      test: ["CMD", "sh", "-c", "redis-cli -a $$REDIS_PASSWORD ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env.prod
    networks:
      - stackcast-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - stackcast-network

volumes:
  redis-data:

networks:
  stackcast-network:
    driver: bridge
